Feat/create user
f-lab-edu/What-cat-eat pull request #1
Opened 2022-11-15 12:23 UTC by heyoni

2022-11-18 13:26 UTC, f-lab-zion requested changes

2022-11-18 13:26 UTC, f-lab-zion commented on alembic.ini
> +sqlalchemy.url = sqlite:///./myapi.db
File DB를 쓰는걸로 했는데 장단점을 어떻게 생각하셨나요? 여러 대의 서버로 확장했을때 File DB는 어떻게 쓸 수 있을지 생각해보세요

2022-11-18 13:26 UTC, f-lab-zion commented on database.py
> +SQLALCHEMY_DATABASE_URL = "sqlite:///./myapi.db"
위와 마찬가지입니다 서버 확장 시 File DB는 어떻게 할까요?

2022-11-18 13:26 UTC, f-lab-zion commented on domain/user/user_router.py
> +from domain.user import user_crud, user_schema
user_crud, user_schema 에서 필요한 부분만 import 하는게 더 낫지 않을까 싶습니다
디렉토리 구조도 지금이 최선인지 한번 고민해보세요 
다음 프로젝트도 한번 살펴보시면 도움되실겁니다 
https://github.com/tiangolo/full-stack-fastapi-postgresql

2022-11-18 13:26 UTC, f-lab-zion commented on domain/user/user_schema.py
> +    def not_empty(cls, v):
validator 대신 Field를 활용하는 방법도 있습니다. 
`Field(..., min_length=1)`

2022-11-18 13:26 UTC, f-lab-zion commented on domain/user/user_schema.py
> +        if 'password' in values and v != values['password']:
password 가 required로 세팅되어 있는데 중복으로 체크할 필요가 있을까요?

2022-11-18 13:26 UTC, f-lab-zion commented on models.py
> +    updated_at = Column(DateTime, nullable=True)
보통 updated_at 같은 경우 생성될때 created_at 과 동일한 시간을 넣고 수정될때 업데이트 합니다
Column 의 server_default, onupdate 등 인자를 통해 자동 생성되도록 코드를 수정해보세요

2022-11-18 13:27 UTC, f-lab-zion commented
File formatting이 맞지 않습니다 
최소한 flake8, black 에 대해 세팅하시고 커밋한 파일들에 대해서도 적용해보세요

2022-11-27 15:11 UTC, f-lab-zion requested changes
리팩토링은 나중에 진행한다 생각하고 점검이 꼭 필요한 부분 위주로 코멘트 남겼습니다

2022-11-27 15:11 UTC, f-lab-zion commented on .flake8
> +    B950,
ignore가 많은데 의미를 알고 쓰신걸까요?

2022-11-27 15:11 UTC, f-lab-zion commented on README.md
> +$ uvicorn main:app --reload
DB Migration 스크립트가 돌지 않으면 초기 세팅에 문제가 생기지 않을까요?

2022-11-27 15:11 UTC, f-lab-zion commented on api/endpoints/user.py
> +    update_user(user_update=_user_update, id=id, db=db)
update_user 가 있는데 get_user는 역할이 뭔가요?

2022-11-27 15:11 UTC, f-lab-zion commented on crud/crud_user.py
> +    user_create.validate_password(user_create)
validate_password 는 password, password_check 를 인자로 받아서 True/False를 리턴하는 역할을 하는 함수인데요 이걸 굳이 클래스 함수로 만들었을때 어떤 장점이 있을까요? 그리고 password와 password_check는 같은 값이어야 하는 전제조건이 있는데 이정도 로직은 프론트엔드/앱에 맡기고 password 자체만 검증해도 충분하지 않을까요?

2022-11-27 15:11 UTC, f-lab-zion commented on crud/crud_user.py
> +    del user_update.password_check
이것도 password_check를 백엔드에서 체크하지 않으면 굳이 필요없는 부분입니다

2022-11-27 15:11 UTC, f-lab-zion commented on api/endpoints/user.py
> +@router.post("/", status_code=status.HTTP_201_CREATED)
response_model이 필요없나요? 그리고 사용자 생성 시 id는 어떻게 얻나요(user_id 말고 primary key)? 나중에 update, delete, get 모두 primary key로 접근하게 했는데 프론트엔드/앱 관점에서 이 id를 얻을 방법이 있나요?

2022-11-27 15:11 UTC, f-lab-zion commented on crud/crud_user.py
> +        user_update.password = pwd_context.hash(user_update.password)
update 할때만 hash 하나요? create 에서는 이 부분이 없는거 같습니다만

2022-11-27 15:11 UTC, f-lab-zion commented on main.py
> +from api.endpoints.user import router
이름이 router로 import 하면 나중에 user 말고 다른 endpoint들이 늘어나면 어떤 이름으로 import하게 될까요?

2022-11-27 15:11 UTC, f-lab-zion commented on migrations/env.py
> +target_metadata = models.Base.metadata
`  File "migrations/env.py", line 22, in <module>
    target_metadata = models.Base.metadata
AttributeError: module 'models' has no attribute 'Base'
`
이 부분 database에 있는 Base를 가져와서 써야하지 않나요? 제 환경에선 오류가 나는 부분인데 확인 부탁드립니다

2022-11-27 15:11 UTC, f-lab-zion commented on migrations/versions/a25da289224b_.py
> +    sa.Column('id', sa.Integer(), nullable=False),
Primary key를 integer로 쓸때와 UUID로 쓸때의 장단점을 조사해보세요
다음 링크도 한번 읽어보세요 
[choose-primary-key-uuid-or-auto-increment](https://www.bytebase.com/blog/choose-primary-key-uuid-or-auto-increment)

2022-11-27 15:11 UTC, f-lab-zion commented on migrations/versions/a25da289224b_.py
> +    sa.Column('updated_at', sa.DateTime(), nullable=True),
model에서는 nullable False 인데 여기는 True네요?

2022-11-27 15:11 UTC, f-lab-zion commented on requirements.txt
> +virtualenv==20.16.7
이거 정말 꼭 필요한 패키지만 쓰여있는걸까요? 꼭 필요한 패키지만 적는게 중요합니다

2022-11-27 15:11 UTC, f-lab-zion commented on schema/user.py
> +        return values.password
이 함수가 UserBase에 위치하는게 가장 적합한지 고민해보세요

2022-11-27 15:11 UTC, f-lab-zion commented on schema/user.py
> +    user_id: str = Field(default=None, max_lenght=15)
오타 max_lenght -> max_length 
테스트 케이스가 세부적인 것까지 잡아주지 못해서 거르지 못한 결과입니다

2022-11-27 15:11 UTC, f-lab-zion commented on tests/test_user.py
> +
============================================================================== short test summary info ==============================================================================
FAILED tests/test_user.py::test_dont_match_password - assert 409 == 400
FAILED tests/test_user.py::test_short_password - assert 409 == 400
FAILED tests/test_user.py::test_without_lowercases_in_password - assert 409 == 400
FAILED tests/test_user.py::test_without_numbers_in_password - assert 409 == 400
FAILED tests/test_user.py::test_create_user - assert 409 == 201
FAILED tests/test_user.py::test_get_user - AssertionError: assert {'id': 1, 'ni...uccess?oh111'} == {'id': 1, 'ni...: 'test_user'}
============================================================================ 6 failed, 3 passed in 0.66s ============================================================================

테스트 케이스 오류가 6건 잡히네요

2022-11-28 04:03 UTC, f-lab-zion commented
이미 올라간 .DS_Store 는 제거해주세요

2022-11-28 09:06 UTC, heyoni commented on .flake8
> +    B950,
sider라는 회사에서 추천해준 ignore를 사용했습니다..[(sider recommend flake8)](https://github.com/sider/runners/blob/bdc863bd5faf78f820fc05dcfad7cd5a27613f78/images/flake8/sider_recommended_flake8.ini)
ignore에 관해 찾아보고 필요한 기능만 넣어두었습니다.

2022-11-28 10:07 UTC, heyoni commented on api/endpoints/user.py
> +    update_user(user_update=_user_update, id=id, db=db)
사용자가 없을 경우 에러처리를 get_user에서 해주었습니다.
지금은 변경된 부분입니다!

2022-11-28 10:10 UTC, heyoni commented on crud/crud_user.py
> +    user_create.validate_password(user_create)
클래스함수로 만들게 되면 코드중복이 줄어들고 재사용성이 줄어드는 것으로 알고있습니다. update 부분에서도 사용해야 해서 클래스 함수로 작성했습니다. 그냥 일반 함수로 빼는 편이 좋을까요?
그리고 프론트에서 체크해주었다고 해도 백에서 이중으로 체크해주지 않아도 되나요?

2022-11-28 10:10 UTC, heyoni commented on crud/crud_user.py
> +    del user_update.password_check
넵 확인했습니다.

2022-11-28 10:10 UTC, heyoni commented on migrations/versions/a25da289224b_.py
> +    sa.Column('updated_at', sa.DateTime(), nullable=True),
DB 마이그레이션 작업이 빠져있었습니다! 확인했습니다.

2022-11-28 10:11 UTC, heyoni commented on requirements.txt
> +virtualenv==20.16.7
넵 pip install fastapi로 설치를 해버려서 패키지가 많이 설치된 것 같습니다. 확인해보고 필요없는 패키지는 삭제하겠습니다.

2022-11-28 13:16 UTC, heyoni commented on crud/crud_user.py
> +        user_update.password = pwd_context.hash(user_update.password)
create에도 hash를 하고 있습니다!

2022-11-29 01:40 UTC, f-lab-zion commented on api/endpoints/user.py
> +    update_user(user_update=_user_update, id=id, db=db)
변경된걸 커밋해주셔야 제가 확인할 수 있습니다

2022-11-29 01:40 UTC, f-lab-zion commented on crud/crud_user.py
> +    user_create.validate_password(user_create)
validate_password 의 경우 parameter 가 password만 필요하고 클래스의 변수나 다른 함수와 연동 부분이 없는데 굳이 클래스 함수로 만드는게 필요할까 싶네요. create, update 에서 사용한다고 클래스 함수로 만들 필요는 없습니다 
password_check 의 경우 password, password_check를 보내는 프론트 입장에서도 얼마든지 같은지 비교가 가능할텐데 백엔드에서 이중으로 체크하는 의미가 있을까요? 복잡한 로직이 필요없는 단순 비교 정도는 이중 체크할 필요가 없습니다

2022-11-29 09:02 UTC, heyoni commented on api/endpoints/user.py
> +    update_user(user_update=_user_update, id=id, db=db)
새로 작성한 브랜치에서 수정하여서 이번 커밋에는 올리지 못했습니다.

2022-11-29 09:02 UTC, heyoni commented on main.py
> +from api.endpoints.user import router
넵 확인했습니다. 이것도 새 브랜치에서 수정한 내용입니다!

2022-11-29 09:43 UTC, heyoni commented on schema/user.py
> +    user_id: str = Field(default=None, max_lenght=15)
넵 테스트코드 추가하겠습니다.

2022-12-02 08:27 UTC, heyoni commented on crud/crud_user.py
> +    user_create.validate_password(user_create)
넵 확인했습니다. 그러면 password가 맞는지 체크하는 부분 이외에 비밀번호 길이가 짧거나 숫자, 영소문자가 들어갔는지 확인하는 부분은 그대로 백엔드에서 확인해주는 것이 맞나요?

2022-12-02 08:29 UTC, heyoni commented on api/endpoints/user.py
> +@router.post("/", status_code=status.HTTP_201_CREATED)
네 기능 추가하겠습니다! 로그인 이후 response_model을 이용해 pk 값을 local storage에 넘겨주는 방법을 생각하고 있습니다!

2022-12-02 08:30 UTC, heyoni commented on migrations/versions/a25da289224b_.py
> +    sa.Column('id', sa.Integer(), nullable=False),
### UUID와 Primary Key

1. UUID
    - 데이터에 대한 정보가 없음 → 보안상 안전
    - Stateless하다. → 함수를 사용하여 키를 생성함. pk는 DB 조회시에만 키를 알 수 있음
    - (단점) 메모리를 많이 사용
2. PK
    - DB가 여러개일 경우에는 pk 충돌 가능성이 있음

** 중요 ** 테이블의 pk는 노출되어서는 안된다. 노출 시 변경 비용이 급상승함.

결론 → application 내부용 키는 pk, 외부에 공개할 키는 uuid로 변경하는 것이 좋음
----
해당 링크를 읽고 이렇게 정리했습니다.
uuid 값도 추가해보도록 하겠습니다!

2022-12-02 08:31 UTC, heyoni commented on tests/test_user.py
> +
pytest mock으로 테스트 해본 뒤 다시 올리겠습니다!

2022-12-02 10:05 UTC, heyoni commented on README.md
> +$ uvicorn main:app --reload
수정했습니다!

2022-12-02 11:42 UTC, mihosang commented on crud/crud_user.py
> +    user_create.validate_password(user_create)
넵 맞습니다 비밀번호 검증은 백엔드에서 진행합니다

2022-12-02 11:44 UTC, f-lab-zion commented on crud/crud_user.py
> +    user_create.validate_password(user_create)
넵 맞습니다 비밀번호 검증은 백엔드에서 진행합니다

2022-12-15 12:11 UTC, f-lab-zion approved these changes
일단 approve 하고 앞으로 해야할 action items를 전달하는걸로 하겠습니다
머지하기 전에 다음 에러는 꼭 해결해주세요 
아마 config 파일 추가를 잊으신거 같네요 

`Traceback (most recent call last):
  File "/Users/mihosang/PycharmProjects/What-cat-eat/main.py", line 2, in <module>
    from api.v1.endpoints import user
  File "/Users/mihosang/PycharmProjects/What-cat-eat/api/v1/endpoints/user.py", line 3, in <module>
    from database import get_db
  File "/Users/mihosang/PycharmProjects/What-cat-eat/database.py", line 7, in <module>
    SQLALCHEMY_DATABASE_URL = config('SQLALCHEMY_DATABASE_URL')
  File "/Users/mihosang/PycharmProjects/What-cat-eat/venv/lib/python3.9/site-packages/starlette/config.py", line 98, in __call__
    return self.get(key, cast, default)
  File "/Users/mihosang/PycharmProjects/What-cat-eat/venv/lib/python3.9/site-packages/starlette/config.py", line 114, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'SQLALCHEMY_DATABASE_URL' is missing, and has no default."
`

다음 필수로 수행해야할 action item은 github action으로 feature/* 브랜치에 커밋될때마다  pytest 를 돌린 결과가 all pass 인지 여부를 알려주도록 추가합시다

2022-12-21 10:09 UTC, merged