Feat/#10 ci/cd 적용
f-lab-edu/What-cat-eat pull request #18
Opened 2023-01-07 03:00 UTC by heyoni

- #10 
- #11 
- #12

2023-01-07 11:49 UTC, mihosang requested changes
.

2023-01-07 11:49 UTC, mihosang commented on dockerfile
> +CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
docker build  후 docker run 해보셨을까요?
DB 연결에서 오류가 납니다
DB 연결에 필요한 정보를 어떻게 넘겨야 해결할 수 있을지 조사해보세요

2023-01-07 11:49 UTC, mihosang commented on repositories/UserRepository.py
>          user = self._user[id - 1]
parameter 의 user, local 변수로서의 user가 중복

2023-01-07 11:55 UTC, f-lab-zion requested changes
몇가지 확인 부탁드립니다

2023-01-07 11:55 UTC, f-lab-zion commented on dockerfile
> +CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
docker build & run  해보셨을까요?
DB 연결에 필요한 정보를 전달해줘야 하는데 어떤 방법을 사용할 수 있는지 조사해보세요

2023-01-07 11:55 UTC, f-lab-zion commented on repositories/UserRepository.py
>          user = self._user[id - 1]
param 의 user와 local 변수의 user가 중복

2023-01-08 12:47 UTC, heyoni commented on dockerfile
> +CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
넵 찾아보겠습니다!

2023-01-09 01:54 UTC, f-lab-zion commented on dockerfile
> +CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
혹시 이것도 해결하셨나요?

2023-01-09 13:52 UTC, heyoni commented on dockerfile
> +CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
아직 찾아보고 있는 중인데 작성 후 이번 PR에 같이 올릴까요?

2023-01-09 14:36 UTC, f-lab-zion approved these changes
👍 수고하셨습니다 Docker 파일은 다른 PR에서 따로 확인하겠습니다

2023-01-09 14:52 UTC, merged