Feat/#15 user login 기능 작성
f-lab-edu/What-cat-eat pull request #21
Opened 2023-01-13 14:38 UTC by heyoni

## Definition
- #15

2023-01-16 08:16 UTC, f-lab-zion requested changes
👍 수고하셨습니다. 몇가지 코멘트만 확인해주세요 
그리고 login 으로 얻은 access_key를 사용하는 코드도 차후 다른 PR로 올려주세요

2023-01-16 08:16 UTC, f-lab-zion commented on schema/login.py
> +        orm_mode = True
Login 클래스는 Response Model을 정의하기 위해 사용한 것으로 보입니다 `orm_mode=True` 로 설정한 이유가 있을까요?

2023-01-16 08:16 UTC, f-lab-zion commented on services/LoginService.py
> +    def login(self, form_data: OAuth2PasswordRequestForm = Depends()):
return type을 명시하면 좋겠습니다
또한 dict를 리턴하고 있는데 `Login` 이 되어야 하지 않을까요?

2023-01-16 08:16 UTC, f-lab-zion commented on services/LoginService.py
> +            )
이 경우는 `create_access_token` 의 parameter 인 `expires_delta` 의 default 값을 `settings.ACCESS_TOKEN_EXPIRE_MINUTES` 로 정의하면 if-else 구문을 뺄 수 있습니다

2023-01-16 08:16 UTC, f-lab-zion commented on services/LoginService.py
> +pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
전역변수로 사용될 필요가 없어보입니다
LoginService 클래스 안으로 넣어도 되지 않을까요?

2023-01-16 08:16 UTC, f-lab-zion commented on tests/test_login.py
> +
`username`, `password` 중 하나 또는 둘다 입력되지 않은 케이스에 대한 테스트 케이스가 추가되면 어떨까요?

2023-01-17 11:37 UTC, heyoni commented on schema/login.py
> +        orm_mode = True
orm_mode 관련 질문을 하고 지운다는걸 넣어버렸습니다! 수정하겠습니다!

2023-01-17 11:37 UTC, heyoni commented on services/LoginService.py
> +    def login(self, form_data: OAuth2PasswordRequestForm = Depends()):
넵 수정했습니다~!

2023-01-17 12:16 UTC, heyoni commented on services/LoginService.py
> +            )
감사합니다!

2023-01-27 01:52 UTC, f-lab-zion approved these changes
👍 좋아보입니다 
단순 코멘트만 몇개 달았으니 확인해보시고 머지하셔도 좋습니다 
수고하셨습니다

2023-01-27 01:52 UTC, f-lab-zion commented on services/UserServices.py
> +        req_user = self.get(int(decoded_token["sub"]))
잘못된 토큰이 오거나 토큰의 내용 중 `sub`키가 없는 경우를 대비하여 
Exception 처리를 해서 `raise HTTPException(...)` 해두면 어떨까요?

2023-01-27 01:52 UTC, f-lab-zion commented on api/v1/endpoints/user.py
> +    return userService.get_current_user(token)
지금은 user API만 있어서 여기에 둬도 괜찮습니다만 나중에 다른 API 에서도 이 함수를 Depends 하게 될텐데 함수 위치를 조정하는건 어떨까 싶습니다

2023-01-27 01:52 UTC, f-lab-zion commented on api/v1/endpoints/user.py
> +    req_user: str = Depends(get_current_user),
변수 Naming은 그 의미를 명확히 담고 있는게 좋다고 생각합니다 
`req_user` 보다는 `current_user` 가 좀더 명확하지 않을까요? (단순 제안입니다)

2023-01-30 14:32 UTC, heyoni commented on api/v1/endpoints/user.py
> +    return userService.get_current_user(token)
상위 계층인 endpoint로 옮기는게 맞을까요??

2023-01-30 15:14 UTC, f-lab-zion commented on api/v1/endpoints/user.py
> +    return userService.get_current_user(token)
어떤 방식으로 정리할지는 정답으로 정해진건 없습니다 
만약 저라면 `/api/deps.py` 를 만들어서 `database.py` 에 있는 `get_db` 와 `api/v1/endpoints/user.py` 에 있는 `get_current_user` 를 함께 위치해두고 Depends()로 불러올 함수들을 한 군데 모아두는 것을 선호할 것 같습니다.
꼭 제 의견을 따를 필요는 없고 @heyoni 님이 생각하기에 좋은 방식으로 정리해두셔도 무방합니다

2023-02-02 16:10 UTC, merged