Feat/#22 고양이 정보 crud 작성
f-lab-edu/What-cat-eat pull request #26
Opened 2023-02-20 16:20 UTC by heyoni

## Definition
- #22

2023-02-24 17:47 UTC, f-lab-zion requested changes
👍 수고하셨습니다 상세 내용은 코멘트를 참고해주세요

2023-02-24 17:47 UTC, f-lab-zion commented on api/deps.py
> +#     id = int(decoded_token["sub"])
코드를 주석처리 하는 것은 지양해야 합니다
나중에 참고할 필요가 있는 코드면 history에서 조회할 수 도 있는데 굳이 남겨둘 필요가 없죠

2023-02-24 17:47 UTC, f-lab-zion commented on api/deps.py
> +    return token_data.user_id
TokenData를 쓸 필요가 없어보입니다

2023-02-24 17:47 UTC, f-lab-zion commented on repositories/UserRepository.py
> +            user = None
Exception 으로 처리하는 방법 외에 `self._user` 의 length 를 이용하여 미리 체크하는 방식도 있습니다

2023-02-24 17:47 UTC, f-lab-zion commented on repositories/CatRepository.py
> +        return user
UserRepository의 함수와 역할이 동일해 보입니다

2023-02-24 17:47 UTC, f-lab-zion commented on services/CatServices.py
> +        user = self.catRepository.get_user_by_user_id(current_user_id)
CatService 가 꼭 CatRepository만 접근할 필요는 없습니다
경우에 따라 UserRepository에 접근해도 됩니다

2023-02-24 17:47 UTC, f-lab-zion commented on services/CatServices.py
> +        return self.catRepository.delete(id)
대표 고양이가 지워질 경우 남은 고양이 중에 대표 고양이를 결정해야 하지 않나요?

2023-02-25 07:41 UTC, heyoni commented on repositories/UserRepository.py
> +            user = None
try except를 사용하는 것 보다는 raise exception이 더 효율적인가요?

2023-02-25 16:31 UTC, f-lab-zion commented on repositories/UserRepository.py
> +            user = None
이 경우 index인 `id` 가 0보다 작거나 `len(self._user)` 보다 크다면 return None 하고 그렇지 않으면 `return self._user[id - 1]`으로 처리하면 의미가 더 명확할 수 있다는 의미입니다. 물론 `IndexError` 가 해당 케이스를 exception으로 잡아주는 것은 자명합니다만 코드의 가독성과 협업 측면에서는 의미를 보다 명확하게 드러나는 코드가 좋아보입니다. 이건 코드 스타일에 대한 문제라서 어느 것이 옳다 그르다를 말하기 어렵습니다만 하나의 의견으로 들어주세요.

2023-02-25 17:40 UTC, heyoni commented on services/CatServices.py
> +        return self.catRepository.delete(id)
고양이가 한마리만 있을 경우도 있기 때문에 대표고양이 설정은 유저 선택에 맡길 예정입니다!
(대표고양이가 설정이 안되어있으면 UI로 '대표고양이 설정이 필요합니다'라는 안내가 나갈 예정입니다.)

2023-03-05 14:41 UTC, f-lab-zion approved these changes
👍 좋아보입니다

2023-03-08 15:44 UTC, merged