Feat/#7 클린 아키텍쳐 적용
f-lab-edu/What-cat-eat pull request #9
Opened 2022-12-25 15:50 UTC by heyoni

## 클린아키텍쳐 적용
- #8
- #7
- #6

## TODO
- Git Action 테스트 자동확
- docker

2022-12-27 15:30 UTC, f-lab-zion requested changes
클린 아키텍처 적용이 좋아보입니다. 리뷰하기도 상당히 편해졌네요 
디테일한 부분 comment 드렸으니 살펴보시기 바랍니다.

2022-12-27 15:30 UTC, f-lab-zion commented on .github/workflow/test_before_commit.yml
> +      - run: python -m pytest
[actions:python-app](https://github.com/f-lab-edu/What-cat-eat/new/develop?filename=.github%2Fworkflows%2Fpython-app.yml&workflow_template=ci%2Fpython-app
)
위 링크를 참고하셔서 pip upgrade, pip install requirements, flake8, black, pytest를 순차적으로 테스트하도록 수정해보세요

2022-12-27 15:30 UTC, f-lab-zion commented on repositories/UserRepository.py
> +    def create(self, user: User):
범용적인 abstract method에 User라는 클래스는 어울리지 않습니다

2022-12-27 15:30 UTC, f-lab-zion commented on repositories/UserRepository.py
> +    def get_value(self, user: User, nickname: str = None, user_id: str = None) -> User:
nickname 검색과 user_id 검색을 하나로 할 필요가 있을까요? 두개를 or 조건을 걸면 어떤게 먼저 나올지 예측이 될까요?

2022-12-27 15:30 UTC, f-lab-zion commented on services/UserServices.py
> +        validate_password(user_body)
validate_password 의 parameter로 user_body를 넘길게 아니라 user_body.password를 넘기는게 역할이 더 명확해보입니다
validate_password 함수에서도 Exception 을 raise 하기 보다는 True/False의 Boolean return하여 create, update 함수에서 return value에 따라 분기하는게 좋아보입니다

2022-12-27 15:30 UTC, f-lab-zion commented on services/UserServices.py
> +        validate_password(user_body)
위와 동일

2022-12-27 15:30 UTC, f-lab-zion commented on api/v1/endpoints/user.py
> +def create_user(user: UserCreate, userService: UserService = Depends()):
UserCreate 에는 user_id만 있는데 password, nickname은 어디서 받나요?

2022-12-27 15:30 UTC, f-lab-zion commented on api/v1/endpoints/user.py
> +def update_user(id: int, user_body: UserUpdate, userService: UserService = Depends()):
UserUpdate 도 비어있는거 같습니다. model 쪽 확인 부탁드려요

2022-12-28 04:16 UTC, heyoni commented on api/v1/endpoints/user.py
> +def create_user(user: UserCreate, userService: UserService = Depends()):
UserBase를 상속받고 있습니다. 변경해야 할까요?
`class UserBase(BaseModel):
    id: Optional[int] = Field(primary_key=True)
    nickname: str = Field(min_length=1, max_length=15)
    password: str


class UserCreate(UserBase):
    user_id: str = Field(min_length=1, max_length=15)`

2022-12-28 04:17 UTC, heyoni commented on api/v1/endpoints/user.py
> +def update_user(id: int, user_body: UserUpdate, userService: UserService = Depends()):
여기도 UserBase를 상속받고 있습니다.
```python
class UserUpdate(UserBase):
    pass
```

2022-12-28 04:20 UTC, heyoni commented on services/UserServices.py
> +        validate_password(user_body)
넵 확인했습니다!

2022-12-28 04:38 UTC, f-lab-zion commented on api/v1/endpoints/user.py
> +def create_user(user: UserCreate, userService: UserService = Depends()):
아 이건 제가 놓쳤네요 확인했습니다 변경하실 필요 없습니다

2022-12-28 06:54 UTC, heyoni commented on repositories/UserRepository.py
> +    def get_value(self, user: User, nickname: str = None, user_id: str = None) -> User:
이 함수는 nickname, user_id 중복체크를 위해 작성했습니다. 함수명을 바꿀까요? 아니면 nickname혹은 user_id를 받게 되면 user(혹은 False)를 반환하는 함수로 변환할까요?

2022-12-28 08:50 UTC, mihosang commented on repositories/UserRepository.py
> +    def get_value(self, user: User, nickname: str = None, user_id: str = None) -> User:
a라는 유저의 user id와 b라는 유저의 nickname 이 이 함수의 파라미터로 온다면 어떤 동작이 발생할지 예측이 어렵게 되겠죠
이런 경우라면 user id를 받는 함수와 nickname을 받는 함수로 나누는게 의미가 명확하고 side effect 여지를 줄여줍니다

2022-12-28 09:22 UTC, f-lab-zion commented on repositories/UserRepository.py
> +    def get_value(self, user: User, nickname: str = None, user_id: str = None) -> User:
a라는 유저의 user id와 b라는 유저의 nickname 이 이 함수의 파라미터로 동시에 입력되면 어떤 동작이 발생할지 예측이 어렵게 되겠죠
이런 경우라면 user id를 받는 함수와 nickname을 받는 함수로 나누는게 의미가 명확하고 side effect 여지를 줄여줍니다

2022-12-28 09:48 UTC, heyoni commented on .github/workflow/test_before_commit.yml
> +      - run: python -m pytest
넵 :) env 부분은 docker 설정하면서 변경하겠습니다!(다음 PR 예정입니다.)

2022-12-29 03:30 UTC, heyoni commented on repositories/UserRepository.py
> +    def get_value(self, user: User, nickname: str = None, user_id: str = None) -> User:
잘 이해가 가지 않습니다..ㅜㅜ a유저의 user_id랑 b라는 nickname은 결국 get_value를 호출하는 쪽에서 잘못 입력한 것이라 호출한 쪽의 잘못이라 생각되는데요.
만약 나눈다고 해도 똑같이 a유저의 user_id, b유저의 nickname을 입력하게 된다면 똑같은 오류가 나는게 아닌가요?!

2022-12-29 05:57 UTC, heyoni commented on repositories/UserRepository.py
> +    def get_value(self, user: User, nickname: str = None, user_id: str = None) -> User:
이 코드리뷰는 **db를 조회하거나 함수의 역할을 넣어줄 때 두루뭉술하게 하는 것보다는 딱 집어서 해주는게 좋고, 여러가지 파라미터를 넣는 것보다는 명확하게 하나만 하는 게 side effect를 줄일 수 있다.**
라고 이해했고 코드도 알맞게 변경했습니다.

2022-12-29 15:09 UTC, f-lab-zion reviewed
👍 몇가지 코멘트 남깁니다

2022-12-29 15:09 UTC, f-lab-zion commented on repositories/UserRepository.py
> +            return False
return type을 User class로 했으면 여기서도 `return None`이 더 적절할거 같습니다

2022-12-29 15:09 UTC, f-lab-zion commented on repositories/UserRepository.py
> +            return False
위와 동일

2022-12-29 15:09 UTC, f-lab-zion commented on schema/user.py
> +        return {"success": False, "status_code": 400, "error": "비밀번호 길이가 너무 짧습니다."}
dict로 리턴하기 보다는 pydantic model을 쓰면 key를 누락하는 등 실수를 줄일 수 있습니다

2022-12-29 15:09 UTC, f-lab-zion commented on repositories/UserRepository.py
> +    def get_user_by_user_id(self, user: User, user_id: str = None) -> User:
파라미터 중 user: User는 불필요하지 않나요? 어차피 query() 에 들어가는 User class는 상황에 따라 바뀌는 변수가 아닌거 같습니다만

2022-12-29 15:09 UTC, f-lab-zion commented on repositories/UserRepository.py
> +    def get_user_by_nickname(self, user: User, nickname: str = None) -> User:
위와 동일

2022-12-29 15:11 UTC, f-lab-zion approved these changes

2023-01-02 07:17 UTC, merged